# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1189f2cdd87f44bd573585c32a2b4007212216301d0cb8ecd93b6bcb9e918c0138b407be9103af4b59cd93817f41227970c4b4f5f970c8778c7a689998bf45c

test:
  secret_key_base: 9f07e42bb4ac6384ab2f326079fc6e62cc49a544f2be41f404af366f8c8f1e9f17ca1539780f4deb555fab19b8960c23645600a4f1b3cf0894fdfe0b8417174a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
